###Check Action cmd
GET http://localhost:4004/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052


### POSt using action

POST http://localhost:4004/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052/boost
Content-Type: application/json

{}

###Get data

GET http://localhost:4004/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052/largestOrder()


###Get Student Data

GET http://localhost:4004/odata/v4/CatalogService/StudentSet

###Post Data

POST http://localhost:4004/odata/v4/CatalogService/StudentSet
Content-Type: application/json

{
    "DOOR_NO": 433,
    "AREA": "ANSHAN",
    "DISTRICT": "Salem",
    "ID": "5",
    "NAME": "SANDY",
    "CLASS_ID": 4,
    "STANDARD": "10",
    "GENDER": "F"
}


###Delete Data

DELETE http://localhost:4004/odata/v4/CatalogService/StudentSet/5

###Update Data

PATCH  http://localhost:4004/odata/v4/CatalogService/StudentSet/4
Content-Type: application/json

{
    "DOOR_NO": 444,
    "AREA": "ANSHAN",
    "DISTRICT": "Salem",
    "NAME": "SANDY",
    "CLASS_ID": 4,
    "STANDARD": "10",
    "GENDER": "F"
}


