###Check Action cmd
GET http://localhost:4004/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052


### POSt using action

POST http://localhost:4004/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052/boost
Content-Type: application/json

{}

###Get data

GET http://localhost:4004/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052/


###Get Student Data

GET http://localhost:4004/odata/v4/CatalogService/StudentSet

###Post Data

POST http://localhost:4004/odata/v4/CatalogService/StudentSet
Content-Type: application/json

{
    "DOOR_NO": 433,
    "AREA": "ANSHAN",
    "DISTRICT": "Salem",
    "ID": "5",
    "NAME": "SANDY",
    "CLASS_ID": 4,
    "STANDARD": "10",
    "GENDER": "F"
}


###Delete Data

DELETE http://localhost:4004/odata/v4/CatalogService/StudentSet/5

###Update Data

PATCH  http://localhost:4004/odata/v4/CatalogService/StudentSet/4
Content-Type: application/json

{
    "DOOR_NO": 444,
    "AREA": "ANSHAN",
    "DISTRICT": "Salem",
    "NAME": "SANDY",
    "CLASS_ID": 4,
    "STANDARD": "10",
    "GENDER": "F"
}


###
GET http://localhost:4004/odata/v4/MyServices/EmployeeSet


### Post Generic Handlers - before
POST http://localhost:4004/odata/v4/MyServices/EmployeeSet
Content-Type: application/json

{
      "nameFirst": "Praveen",
      "nameMiddle": null,
      "nameLast": "Spring",
      "nameInitials": null,
      "sex": "F",
      "language": "E",
      "phoneNumber": "+1 224 374 524",
      "email": "sally.spring@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "USD",
      "salaryAmount": 1000000,
      "accountNumber": "111222333",
      "bankId": "510000633",
      "bankName": "My Bank of Antioch"
}

###ON

GET http://localhost:4004/odata/v4/MyServices/ReadEmployeeSet

###

GET http://localhost:4004/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052

### Post Boost

POST http://localhost:4004/v2/odata/v4/CatalogService/PurchaseSet/74867AD200E41EDBA5D8B0C98DC28052/boost
Content-Type: application/json

{}


### Get Data in Employee

GET http://localhost:4004/odata/v4/MyServices/EmployeeSet

### Add Data in Employee

POST http://localhost:4004/odata/v4/MyServices/EmployeeSet
Content-Type: application/json

{
      "nameFirst": "John",
      "nameMiddle": null,
      "nameLast": "Spring",
      "nameInitials": null,
      "sex": "M",
      "language": "E",
      "phoneNumber": "+1 224 374 524",
      "email": "sally.spring@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "INR",
      "salaryAmount": 100000,
      "accountNumber": "111222313",
      "bankId": "510000623",
      "bankName": "My Bank of India"
}



###Test Security : Authentication and Authorization
http://localhost:4004/odata/v4/CatalogService/EmployeesSet
Authorization: Basic kumar:






